version: '3.8'

services:
  webapi:
    build:
      context: .
      dockerfile: FireComponent/Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000    
    networks:
      - fire-network

networks:
  fire-network:
    driver: bridge